# Practical session week 2 - Rectangular data and Pandas

## Purpose
Give an introduction to  
* Jupyter Notebook
* Rectangular data
* Variables and records
* Independent and dependent variables
* Pandas and Numpy Libraries
* Exploratory Data Analysis

## Methodology
We will use the Pandas library to load a dataset, perform operations, and conduct some data analysis. Some challenges are presented at the end.

## Results
Practical knowledge of how to load, write, and manipulate rectangular data in Python. This is our first hands-on session with real data.

## Suggested next steps
The next step is to explore data visualizations such as bar charts for category counts, histograms for numeric distributions, and scatter plots for relationships between two numeric variables. This will be the topic of next week.

# Jupyter Notebooks

For this notebook, use a Python environment with Jupyter, NumPy, and Pandas installed. Anaconda is one possible environment manager, but any environment containing these packages will work.

JupyterLab or Jupyter Notebook will be our preferred working environment.

Jupyter Notebooks are composed of cells.

Cells can contain Markdown or code.  

- **Markdown cells** contain explanations, headings, lists, links, images, and formulas. Useful syntax includes `# Heading`, `**bold**`, `*italic*`, `` `code` ``, and `- list item`.

- **Code cells** contain Python instructions that can be executed. The result appears directly below the cell.

The shortcuts below are enough for the activities in this notebook:

Useful Jupyter Notebook shortcuts:
- `Enter`: edit the selected cell.
- `Esc`: leave edit mode and enter command mode.
- `A`: create a cell above the current cell while in command mode.
- `B`: create a cell below the current cell while in command mode.
- `Shift + Enter`: execute the cell and move to the next one.
- `Ctrl + Enter`: execute the cell and remain on it.
- `D`, `D`: delete the selected cell while in command mode.
- `Z`: undo a deleted cell while in command mode.

## Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. Also, it offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

In [1]:
import numpy as np

For one-dimensional arrays, `np.dot(a, b)` multiplies corresponding values and adds the products, producing the dot product. Use `help(np.dot)` in the next cell to display the function's explanation and parameters without leaving the notebook.

## Before moving forward

Explore Numpy `dot` function

In [2]:
v1 = [1,2,3,4]
v2 = [3,2,5,4]

# "np" is the alias for numpy library when imported like 'import numpy as np'
# print the dot product of v1 and v2 using numpy
# compare with the dot function you did in the last class
print(np.dot(v1, v2))

38

In [ ]:
help(np.dot)

Explore Numpy functions `linalg.norm` to obtain the magnitude/norm of the vectors `v1` and `v2`

In [5]:
# compare with the norm function you did in the last class
print(np.linalg.norm(v1))
print(np.linalg.norm(v2))

5.477225575051661
7.3484692283495345

Consider the cosine similarity function we build from scrach last week:

$$
  cos(v1, v2) = \frac{v1 . v2}{\lVert v1 \rVert \times \lVert v2 \rVert}
$$

Explore Numpy functions `linalg.norm` e `dot` and **re-write the cosine function** below without using a `for` loop.

In [8]:
print((np.dot(v1, v2))/ (np.linalg.norm(v1) * np.linalg.norm(v2)))

0.9441175904999112

## Rectangular data

Many datasets used in Data Science are tabular, like a spreadsheet or database table. A rectangular dataset has rows and columns. If it has `n` rows and `m` columns, its dimensions are `n × m`.

* A **column** in the table is commonly referred to as a **variable**.
    * A variable may also be called an attribute, input, predictor, or feature.
* A **row** in the table is commonly referred to as a **record**.
    * A record may also be called a case, example, instance, observation, pattern, or sample.


A rectangular dataset can therefore be understood as a two-dimensional structure: rows identify observations and columns describe characteristics of those observations.

What are independent and dependent variables?  

<details>
<p>
    
- An **independent variable** is used to explain or predict another variable. In an experiment, it may be changed or controlled to observe its effect.  
    
- A **dependent variable** is the result being measured, explained, or predicted.
    
</p>
</details>

In Data Science, we often investigate how independent variables relate to or help predict a dependent variable.

What other names are given to these variables?

<details>
<p>

An **independent variable** may also be called a predictor, explanatory variable, feature, input, covariate, or risk factor.
    
A **dependent variable** may also be called a response, outcome, target, label, or output.


    
</p>
</details>

## Pandas

In [9]:
import pandas as pd

What is Pandas?

Pandas is a Python library for organizing, cleaning, transforming, and analyzing tabular data. Its two main data structures are:

- **Series**: a one-dimensional sequence of values with labels. A single DataFrame column is a Series.
- **DataFrame**: a two-dimensional table with labeled rows and columns. Different columns may contain different data types.

In this notebook, Pandas will be used to create DataFrames, read and write CSV files, inspect datasets, select rows and columns, and filter records using logical conditions. You can inspect any Pandas object or function inside Jupyter with `help(...)` or by placing `?` after its name, for example `pd.DataFrame?`.

### Lets use Pandas to create a retangular dataset

The DataFrame object is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table. It is generally the most commonly used pandas object.

#### Constructing DataFrame

A Pandas DataFrame can be constructed in a variety of ways.

One of them is from a list of dicts:

Let's create a DataFrame from a list of dictionaries. Each dictionary represents a record and the keys represent the variables.

Desired DataFrame:

```python
     a	b
0	0	0
1	1	2
2	2	4
```

In [10]:
# create dataframe from a list of dictionaries to obtain the following output
#    a  b
# 0  0  0
# 1  1  2
# 2  2  4

dic = {
    'a': [0,1,2],
    'b': [0,2,4],
}
# what should the items in the list be to obtain the output above?
data = []

# use pd.DataFrame to create a dataframe from the "data"
df = pd.DataFrame(data=dic)

df

   a  b
0  0  0
1  1  2
2  2  4

Pandas creates tabular data structures called DataFrames and missing values are represented as `NaN` (**Not a Number**)
- if you don't provide values for a column, pandas will fill it with `NaN`
- Handling missing values is a big part of data cleaning and preparation process and defining strategies to deal with them are really important.

In [16]:
df = pd.DataFrame([{'a': 1, 'b': 2, 'c': 3},
                   {'a': 0, 'b': 3, 'c': 4},
                   {'a': 3, 'b': 5, 'c': 7}])

In [17]:
df

   a  b  c
0  1  2  3
1  0  3  4
2  3  5  7

A DataFrame object has has an `index` and a `column` attribute
- `index` indicates the start, end (exclusive) and increment of the row indices

In [18]:
df.index

RangeIndex(start=0, stop=3, step=1)

- `columns` indicates the **column names** of the DataFrame and can be used to access columns

In [22]:
df.columns

Index(['a', 'b', 'c'], dtype='object')

**Casting to other data types** may help when working with those columns, try casting `df.columns` to a list

In [23]:
list(df.columns)

['a', 'b', 'c']

We can **rename** columns using the `rename` method

- Note that the columns were defined by the dictionary keys
- `inplace=True` will modify the DataFrame **in place**, otherwise a new DataFrame will be returned and the original will remain unchanged

In [ ]:
# before:
df = pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

In [28]:
# after - use rename to rename the columns 'a' to 'data' and 'b' to 'science'
df.rename({'a': 'data', 'b': 'science'}, axis=1, inplace=True)

df

   data  science  c
0     1        2  3
1     0        3  4
2     3        5  7

#### Creating your own DataFrame

Before learning more details and operations on DataFrames, lets create our own.

In [29]:
#       name	shoe	height
#   0	ana	    38  	  168
#   1	bruno   39	    170
#   2	carlos	42	    174

name_list = ['ana', 'bruno', 'carlos']
shoe_list = [38,39,42]
height_list = [168,170,174]
gender_list = ['F', 'M', 'F']

# we are going to create a dataframe from the lists above - what should be the "keys" and "values" of the dictionary?
students_df = pd.DataFrame({'name': name_list, 'shoe': shoe_list, 'height': height_list, 'gender': gender_list})
students_df

     name  shoe  height gender
0     ana    38     168      F
1   bruno    39     170      M
2  carlos    42     174      F

Print the `columns` of the DataFrame

Index(['name', 'shoe', 'height', 'gender'], dtype='object')

Print the `index` of the DataFrame

RangeIndex(start=0, stop=3, step=1)

We forgot the **gender data**. This is how we can add a new column to the DataFrame after it has been created

     name  shoe  height  gender
0     ana    38     168  female
1   bruno    39     170    male
2  carlos    42     174    male

We may have also introduced a wrong value. We can **access** it or **change** it using `loc`

In [37]:
students_df.loc[2]

name      carlos
shoe          42
height       174
gender         F
Name: 2, dtype: object

We can also use the `iloc` method to access data by **position**
- use `iloc` to access the last row of the DataFrame

In [38]:
students_df.iloc[-1]

name      carlos
shoe          42
height       174
gender         F
Name: 2, dtype: object

- Use `iloc` to access the last element of the last column of the DataFrame
    
    - **Tip**: the DataFrame is matrix-like, so you can use the same indexing as you would use in a matrix (even negative indices work)

/bin/bash: line 1: nano: command not found

## Write and Read a csv file

We can use Pandas to perform both operations.
Run the cell below and check on your folder if the file was created.

In [44]:
# write a DataFrame as a csv file
students_df.to_csv('alunos.csv', index=False)

Read a csv file into a DataFrame - by **default**, `read_csv` assumes that the **delimiter is a comma**

In [45]:
# read the csv file into students_df2
students_df2 = pd.read_csv('alunos.csv')

students_df2

     name  shoe  height gender
0     ana    38     168      F
1   bruno    39     170      M
2  carlos    42     174      F

Let's check if `students_df` is equal to `students_df2` using `.equals` method

In [46]:
students_df.equals(students_df2)

True

When saving a DataFrame to a csv file, we can specify the `index` (`True` | `False`)

## Operations on pandas DataFrames

In this section you will learn about some DataFrame methods like `head` and `tail`.

### Subset of rows (records)

#### Select the first n rows

In [48]:
students_df.head(2)

    name  shoe  height gender
0    ana    38     168      F
1  bruno    39     170      M

#### Select the last rows

In [49]:
students_df.tail(2)

     name  shoe  height gender
1   bruno    39     170      M
2  carlos    42     174      F

#### Get a random sample of n rows

In [67]:
students_df.sample(1,random_state=1000)

     name  shoe  height gender
2  carlos    42     174      F

#### Select rows by position
- select the **first and second rows**

     name  shoe  height gender
1   bruno    39     170   male
2  carlos    42     174   male

#### Select rows that meet logical criteria
- select all students with `height` of **170cm or higher**

In [71]:
students_df[students_df['height'] >= 170]

     name  shoe  height gender
1   bruno    39     170      M
2  carlos    42     174      F

#### Select rows based on multiple conditions
- select all `male` students with `height` of **172cm or higher**

In [78]:
filter_maleAndAbv172 = (students_df['height'] >= 172) & (students_df['gender'] == 'M')

filter_male = students_df['gender'] == 'M'
filter_abvOrEqual172 = students_df.height >= 172

students_df[filter_maleAndAbv172]

Empty DataFrame
Columns: [name, shoe, height, gender]
Index: []

- select all `female` students with `height` of **172cm or higher**

In [82]:
filter_female = students_df.gender == 'F'

students_df[filter_female & filter_abvOrEqual172]

     name  shoe  height gender
2  carlos    42     174      F

### Subset of columns (variables)

#### Select columns by name

In [83]:
students_df['name']

0       ana
1     bruno
2    carlos
Name: name, dtype: object

Select subset of columns `name` and `gender`

In [84]:
students_df[['name', 'gender']]

     name gender
0     ana      F
1   bruno      M
2  carlos      F

#### Select columns by position
Using `iloc[rows, columns]` to select
- select the **first and third columns** of the dataframe

In [91]:
students_df.iloc[:, 0:2]

     name  shoe
0     ana    38
1   bruno    39
2  carlos    42

### Subset of both rows and columns
- select the rows where the `shoe` size is **greater than 40** and **only** the columns `name` and `shoe`

     name  shoe
2  carlos    42

### Summing Up

* When selecting subsets of data, square brackets `[]` are used.
* Inside these brackets, you can use a single column/row label, a list of column/row labels, a slice of labels, a conditional expression or a column.
* Select specific rows and/or columns using **loc** when using the row and column names.
* Select specific rows and/or columns using **iloc** when using the positions in the table.
* You can assign new values to a selection based on **loc/iloc**.

#### Quick reference

```python
df["column"]                              # one column
df[["column_a", "column_b"]]            # multiple columns
df[df["column"] >= value]                 # rows matching one condition
df[(condition_a) & (condition_b)]          # both conditions must be true
df[(condition_a) | (condition_b)]          # at least one condition must be true
df.loc[row_condition, ["column_a", "column_b"]]  # rows and named columns
df.iloc[row_positions, column_positions]   # rows and columns by position
```

Use parentheses around every condition combined with `&` or `|`.

## Challenges

In these challenges you will handle a bigger dataset.

There are a few first questions you need to know how to answer before reading a CSV file with Pandas

- Does the CSV have a header line?
- Is there an index column?
- What is the separator character on the CSV file?
- If there are missing values, is there any specific word being used to describe a missing value?

Then, these details can be handled by specifing some parameters as `sep`, `na_values` or `index_col`.

### Challenge 1 - Load the dataset

In [ ]:
# Your code here
# load titanic dataset

### Challenge 2 - Validate the loading

1. Show the first 10 rows and confirm if the table matches with the lines

In [ ]:
# Your code here

2. Try the DataFrame method `info`. It is a nice alternative. What information do you get from this?

In [ ]:
# Your code here

### Challenge 3 - Some basic EDA

**EDA** stands for `Exploratory Data Analysis`. It is used by data scientists to analyze and investigate data sets and summarize their main characteristics, often employing data visualization methods.

Try executing `df_titanic.describe()`.

In [ ]:
# Your code here

After investigating the results, describe them and comment on the usefulness of this Pandas function.

In [ ]:
# Your comments here

Now, try `.info()` method.

In [ ]:
# Your code here

What information do you get from this?

In [ ]:
# Your comments here

### Challenge 4 - Getting to know your data

What do the results above tell you about each variable? Do you actually know what they mean? Understanding the meaning and encoding of every variable is a crucial step before drawing conclusions from a dataset.

#### Titanic data dictionary

| Variable | Meaning |
|---|---|
| `PassengerId` | Unique identifier assigned to each passenger. |
| `Survived` | Survival outcome: `0` means no and `1` means yes. This can be treated as the dependent or target variable. |
| `Pclass` | Ticket class: `1` = first, `2` = second, and `3` = third class. It can also serve as an approximate indicator of socioeconomic status. |
| `Name` | Passenger's recorded name, often including a title such as Mr., Mrs., or Miss. |
| `Sex` | Passenger's recorded sex: `male` or `female`. |
| `Age` | Age in years. Ages below one year may appear as decimal values. Some ages are missing. |
| `SibSp` | Number of siblings and spouses travelling with the passenger. |
| `Parch` | Number of parents and children travelling with the passenger. |
| `Ticket` | Ticket identifier. Passengers travelling together may share a ticket. |
| `Fare` | Passenger fare. |
| `Cabin` | Cabin number. Most records do not contain a cabin value. |
| `Embarked` | Port of embarkation: `C` = Cherbourg, `Q` = Queenstown, and `S` = Southampton. |

This file contains 891 passenger records. Missing values occur in `Age` (177 records), `Cabin` (687 records), and `Embarked` (2 records). A missing value is not zero; it means that the information was not recorded.

Using the outputs from `info()` and `describe()`, identify which variables are numeric, which are categorical, which contain missing values, and which variables might help explain `Survived`. Write your observations below.

In [ ]:
# Your comments here

---

## Reinforcement exercises - Filtering and selecting data

These exercises revisit the Pandas operations used above. Work through them in order: the filters become gradually more detailed, but every question can be solved with the ideas already introduced in this notebook.

Remember to put each condition inside parentheses when combining conditions with `&` (and) or `|` (or).

### R-01 - First-class passengers

Filter `df_titanic` to show only passengers from first class (`Pclass` equal to `1`).

In [ ]:
# Your code here

### R-02 - Women who survived

Filter the rows for passengers whose `Sex` is `female` **and** whose `Survived` value is `1`.

In [ ]:
# Your code here

### R-03 - Young adults and selected columns

Select passengers aged from 18 to 29, including 18 but excluding 30. Show only the columns `Name`, `Age`, and `Pclass`.

Use `loc` to apply the row filter and select the columns in the same expression.

In [ ]:
# Your code here

### R-04 - Children or older passengers

Select passengers younger than 12 **or** aged 60 and above. Show only `Name`, `Age`, `Sex`, and `Pclass`.

In [ ]:
# Your code here

### R-05 - A more specific passenger profile

Find passengers who travelled in third class, paid a fare greater than 30, **and** survived. Show `Name`, `Pclass`, `Fare`, and `Survived`.

In [ ]:
# Your code here

### R-06 - Women embarking outside Southampton

Select female passengers who embarked at Cherbourg (`C`) **or** Queenstown (`Q`). Show `Name`, `Sex`, `Embarked`, and `Fare`.

Build the two-port condition first, then combine it with the condition for `Sex`.

In [ ]:
# Your code here

### R-07 - Review of selection by position

Using only `iloc`, select the first five rows and the columns in positions 3, 5, and 9 (`Name`, `Age`, and `Fare`).

In [ ]:
# Your code here

### R-08 - Compare two filtered groups

Create two filtered DataFrames:

1. Adult women (`Age` greater than or equal to 18) who survived.
2. Adult women who did not survive.

Use `len` to print the number of rows in each group. Which group is larger?

In [ ]:
# Your code here

### R-09 - Difficult: priority profile

Create one filter for passengers who satisfy **all** of the following:

- they were younger than 16 **or** aged 60 and above;
- they travelled in third class;
- they did not survive.

Show only `Name`, `Age`, `Sex`, `Pclass`, and `Survived`. Store the combined condition in a variable before using `loc`.

In [ ]:
# Your code here

---

## Additional Challenge

These challenges will help you get familiar with the most important object of the NumPy library, the array.

### Part I

1. Use the numpy's function `arange` and create the array `my_array` with the sequence of numbers from 0 to 24.

2. Use the method `reshape` to redimension the array so that it has 6 rows and 4 columns. What happened? What is the relasionship between the number of elements and the dimensions of a 2D matrix?

In [ ]:
my_array = np.arange(24).reshape((6,4))
my_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

###  Part II

$$\begin{bmatrix}
1 & 2 & 1 & 7 \\
3 & 0 & 1 & 8 \\
0 & 2 & 4 & 9 \\
2 & 2 & 5 & 5
\end{bmatrix}$$

1. Create this matrix in NumPy

2. Slice the first column

3. Slice the first column, but only the second and third rows

4. Slice the 4 elements at the center of the matrix

5. Slice the sub-matrix of the 4 elements of the lower right corner, without using the matrix size

6. Slice the sub-matrix of the 4 elements of the upper right corner, without using the matrix size

**Expected output**:

```python

first column:
 [1 3 0 2]

first column, rows 2 and 3:
 [3 0]

centre:
 [[0 1]
 [2 4]]

bottom right:
 [[4 9]
 [5 5]]

bottom right:
 [[4 9]
 [5 5]]

top right:
 [[1 7]
 [1 8]]

top right:
 [[1 7]
 [1 8]]

top right:
 [[1 7]
 [1 8]]
```